version: '3.3'
services:
  myapp:
    image: 'bitnami/codeigniter:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    environment:
      - CODEIGNITER_PROJECT_NAME=fse-inventory
    depends_on:
      - mariadb
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 4306:3306
    volumes:
      - ../fse-inventory-db:/bitnami
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    ports:
      - 8181:80
      - 4433:443
    depends_on:
      - mariadb
    links:
      - mariadb